spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: github-client-id
            clientSecret: github-client-secret
            accessTokenUri: https://github.com/login/oauth/access_token
            userAuthenticationUri: https://github.com/login/oauth/authorize
            userAuthenticationScheme: form
            tokenName: oauth_token
            authenticationScheme: query
          google:
            client-id: google-client-id
            client-secret: google-client-secret

#Homepage URL: http://localhost:8080/
#Authorization callback URL: http://localhost:8080/login/oauth2/code/github

#logging:
#  level:
#    org.springframework.security: DEBUG

#https://github.com/settings/developers
#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#            clientId: github-client-id
#            clientSecret: github-client-secret
#            accessTokenUri: https://github.com/login/oauth/access_token
#            userAuthenticationUri: https://github.com/login/oauth/authorize
#            userAuthenticationScheme: form
#      resource:
#        user-info-uri: https://api.github.com/user
#        prefer-tokem-info: false

# https://github.com/login/device
# https://github.com/login/device/code
# https://github.com/settings/connections/applications/:client_id
