spring:

  # Spring Boot + Spring LDAP configuration application.yml
  ldap:

    # Spring LDAP
    #
    # In this example we use an embedded ldap server. When using a real one,
    # you can configure the settings here.
    #
    # urls: ldap://localhost:12345
    # base: dc=memorynotfound,dc=com
    # username: uid=admin
    # password: secret

    # Embedded Spring LDAP
    embedded:
      #base-dn: dc=memorynotfound,dc=com
      base-dn: dc=springframework,dc=org
      #credential:
        #username: uid=admin
        #password: secret
      #ldif: classpath:schema.ldif
      ldif: test-server.ldif
      #port: 12345
      #port: 8389
      #validation:
        #enabled: false



  # Spring Security - OAuth2 Example Using GitHub | SpringBoot | Java Techie
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: github-client-id
            clientSecret: github-client-secret
            accessTokenUri: https://github.com/login/oauth/access_token
            userAuthenticationUri: https://github.com/login/oauth/authorize
            userAuthenticationScheme: form
            tokenName: oauth_token
            authenticationScheme: query
          google:
            client-id: google-client-id
            client-secret: google-client-secret
#      resource:
#        user-info-uri: https://api.github.com/user
#        prefer-tokem-info: false


#GITHUB
#Homepage URL: http://localhost:8080/
#Authorization callback URL: http://localhost:8080/login/oauth2/code/github
# https://github.com/settings/developers
#  https://github.com/login/device
#  https://github.com/login/device/code
#  https://github.com/settings/connections/applications/:client_id

#logging:
#  level:
#    org.springframework.security: DEBUG
